name: 'box2d windows'
run-name: 'Build box2d for windows'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'read config.json'
        id: config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "config.json"
      - name: 'Checkout source'
        uses: actions/checkout@v4
        with:
          repository: 'erincatto/box2d'
          ref: ${{steps.config.outputs.box2d_tag}}
          fetch-depth: 0
          path: 'source'
      - name: 'cmake configure'
        shell: bash
        run: |
          cmake -S source -B build \
                -A x64 \
                -DCMAKE_CXX_STANDARD=20 \
                -DCMAKE_INSTALL_PREFIX=install \
                -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_SHARED_LIBS=ON \
                -DBOX2D_SAMPLES=OFF \
                -DBOX2D_BENCHMARKS=OFF \
                -DBOX2D_DOCS=OFF \
                -DBOX2D_PROFILE=OFF \
                -DBOX2D_VALIDATE=OFF \
                -DBOX2D_UNIT_TESTS=OFF
          cmake --build build --config Release --parallel
          cmake --install build --config Release
      - name: 'Store source archives'
        uses: actions/upload-artifact@v4
        with:
          name: 'box2d-windows-${{steps.config.outputs.box2d_tag}}'
          path: '${{ github.workspace}}/build'
