### https://github.com/robertying/openssl-curl-android
### https://github.com/jasonacox/Build-OpenSSL-cURL
### https://github.com/leenjewel/openssl_for_ios_and_android

name: 'curl macos'
run-name: 'Build curl for macos'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'read config.json'
        id: config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "config.json"
      - name: 'Setup Ninja'
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.12.1
      - name: 'Checkout source'
        uses: actions/checkout@v4
        with:
          repository: 'curl/curl'
          ref: ${{steps.config.outputs.curl_tag}}
          fetch-depth: 0
          path: 'source'
      - name: 'cmake configure'
        shell: bash
        run: |
          cmake -S source -B build \
                -GNinja \
                -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
                -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=install \
                -DBUILD_CURL_EXE=OFF \
                -DCURL_USE_SECTRANSP=ON \
                -DCURL_DEFAULT_SSL_BACKEND='secure-transport' \
                -DUSE_NGHTTP2=OFF \
                -DCURL_USE_LIBSSH2=OFF \
                -DUSE_LIBIDN2=OFF \
                -DHTTP_ONLY=ON \
                -DBUILD_STATIC_LIBS=ON \
                -DBUILD_SHARED_LIBS=OFF
      - name: 'cmake build'
        shell: bash
        run: cmake --build build --config Release --parallel
      - name: 'cmake install'
        shell: bash
        run: cmake --install build --config Release
      - name: 'Create xcframework'
        shell: bash
        run: |
          xcodebuild -create-xcframework \
                     -library install/lib/libcurl.a \
                     -headers install/include \
                     -output install/xcframework/curl.xcframework \
      - name: 'Store source archives'
        uses: actions/upload-artifact@v4
        with:
          name: 'curl-macos-${{steps.config.outputs.curl_tag}}'
          path: '${{ github.workspace}}/install/xcframework'
