name: 'fmt wasm'
run-name: 'Build fmt for wasm'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'read config.json'
        id: config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "config.json"
      - name: 'Setup Ninja'
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.12.1
      - name: 'Setup Emscripten'
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.62
          actions-cache-folder: 'emsdk-cache'
      - name: 'Checkout source'
        uses: actions/checkout@v4
        with:
          repository: 'fmtlib/fmt'
          ref: ${{steps.config.outputs.fmt_tag}}
          fetch-depth: 0
          path: 'source'
      - name: 'build'
        shell: bash
        run: |
          emcmake cmake -S source -B build \
               -GNinja \
               -DCMAKE_CXX_STANDARD=20 \
               -DCMAKE_INSTALL_PREFIX=install \
               -DCMAKE_BUILD_TYPE=Release \
               -DFMT_DOC=OFF \
               -DFMT_TEST=OFF
          cmake --build build --config Release --parallel
          cmake --install build --config Release
      - name: 'Store source archives'
        uses: actions/upload-artifact@v4
        with:
          name: 'fmt-wasm-${{steps.config.outputs.fmt_tag}}'
          path: '${{ github.workspace}}/install'
