name: 'nghttp2'
run-name: 'Build nghttp2'

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: 'Checkout config'
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'config.json'
      - name: 'read config.json'
        id: config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "config.json"
      - name: 'Setup Developer Command Prompt for Microsoft Visual C++'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: win64
      - name: 'Checkout source'
        uses: actions/checkout@v4
        with:
          repository: 'nghttp2/nghttp2'
          ref: ${{steps.config.outputs.nghttp2_tag}}
          fetch-depth: 0
          path: 'source'
