name: 'openssl'
run-name: 'Build openssl'

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: 'Setup Perl'
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"
      - name: 'Setup perl dependencies'
        shell: bash
        run: cpan -f -i Text::Template
      - name: 'Setup NASM'
        uses: ilammy/setup-nasm@v1
      - name: 'Checkout config'
        uses: actions/checkout@v4
        with:
          path: 'config'
          sparse-checkout: 'openssl'
      - name: 'read config.json'
        id: config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "config/openssl/config.json"
      - name: 'Checkout source'
        uses: actions/checkout@v4
        with:
          repository: 'openssl/openssl'
          ref: ${{steps.config.outputs.openssl_tag}}
          fetch-depth: 0
          path: 'source'
      - name: 'prepare the build directory'
        shell: bash
        run: mkdir build
      - name: 'configure'
        working-directory: build
        shell: bash
        run: |
          perl ../source/Configure VC-WIN64A
      - name: 'build'
        working-directory: build
        shell: bash
        run: nmake
      - name: 'install'
        working-directory: build
        shell: bash
        run: |
          mkdir install
          nmake install DESTDIR=install
      - name: 'Store source archives'
        uses: actions/upload-artifact@v4
        with:
          name: 'openssl-windows-${{steps.config.outputs.openssl_tag}}'
          path: '${{ github.workspace}}/install'