name: 'openssl windows'
run-name: 'Build openssl for windows'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'read config.json'
        id: config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "config.json"
      - name: 'Setup Developer Command Prompt for Microsoft Visual C++'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: win64
      - name: 'Setup Perl'
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"
      - name: 'Setup perl dependencies'
        shell: pwsh
        run: cpan -f -i Text::Template
      - name: 'Setup NASM'
        uses: ilammy/setup-nasm@v1
      - name: 'Checkout source'
        uses: actions/checkout@v4
        with:
          repository: 'openssl/openssl'
          ref: ${{steps.config.outputs.openssl_tag}}
          fetch-depth: 0
          path: 'source'
      - name: 'make dirs'
        shell: bash
        run: |
          mkdir build
          mkdir install
      - name: 'configure'
        working-directory: build
        shell: pwsh
        run: |
          perl ../source/Configure VC-WIN64A
      - name: 'build'
        working-directory: build
        shell: pwsh
        run: |
          set CL=/MP
          nmake build_sw
      - name: 'install'
        working-directory: build
        shell: pwsh
        run: nmake install_sw DESTDIR=../install
      - name: 'Store source archives'
        uses: actions/upload-artifact@v4
        with:
          name: 'openssl-windows-${{steps.config.outputs.openssl_tag}}'
          path: '${{ github.workspace}}/install/Program Files/OpenSSL'
