name: 'sdl2 mixer macos'
run-name: 'Build SDL2 mixer for macos'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: 'Setup Macos dependencies'
        run: |
          brew install \
            autoconf \
            automake \
            libtool \
            pkg-config \
            flac \
            fluidsynth \
            game-music-emu \
            libvorbis \
            libxmp \
            mpg123 \
            opusfile \
            wavpack
      - name: 'Checkout config'
        uses: actions/checkout@v4
        with:
          path: 'config'
          sparse-checkout: 'sdl2_mixer'
      - name: 'read config.json'
        id: config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "config/sdl2_mixer/config.json"
      - name: 'Fetch SDL2'
        shell: pwsh
        run: |
          $url = '${{ steps.config.outputs.sdl_windows_url }}';
          Write-Host $url;
          Invoke-WebRequest $url -OutFile ./sdl.zip;
          Expand-Archive -Path sdl.zip;
      - name: 'Checkout source'
        uses: actions/checkout@v4
        with:
          repository: 'libsdl-org/SDL_mixer'
          ref: ${{steps.config.outputs.sdl_mixer_tag}}
          fetch-depth: 0
          path: 'source'
          submodules: recursive
      - name: 'Patch SDL2_mixer'
        shell: bash
        run: 'cd source && git apply ../config/sdl2_mixer/sdl2_mixer.patch'
      - name: 'xcode build'
        shell: bash
        run: |
          xcodebuild archive \
                     -project source/Xcode/SDL_mixer.xcodeproj \
                     -scheme 'Framework' \
                     -configuration Release \
                     -sdk macosx \
                     -destination 'generic/platform=macOS' \
                     -archivePath "${{ github.workspace}}/SDL2_mixer.xcarchive"
      - name: 'Store source archives'
        uses: actions/upload-artifact@v4
        with:
          name: 'sdl2_mixer-macos-${{steps.config.outputs.sdl_mixer_tag}}'
          path: '${{ github.workspace}}/SDL2_mixer.xcarchive/Products/Library/Frameworks'
