name: 'sdl2'
run-name: 'Create SDL release artifacts'

on:
  workflow_dispatch:
  push:
    paths:
      - sdl2/**

jobs:
  msvc:
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          path: 'config'
          sparse-checkout: 'sdl2/config.json'
      - name: 'read config.json'
        id: config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "config/sdl2/config.json"
      - name: 'Checkout SDL sources'
        uses: actions/checkout@v4
        with:
          repository: 'libsdl-org/SDL'
          ref: ${{steps.json_properties.outputs.tag}}
          fetch-depth: 0
          path: 'source'
      - name: 'cmake configure'
        shell: bash
        run: |
          cmake -S source -B build \
               -DSDL_WERROR=ON \
               -DSDL_STATIC=OFF \
               -DSDL_TEST=OFF \
               -DSDL_TESTS=OFF \
               -DSDL_INSTALL_TESTS=OFF \
               -DSDL2_DISABLE_INSTALL=OFF \
               -A x64 \
               -DCMAKE_INSTALL_PREFIX=install \
               -DCMAKE_BUILD_TYPE=Release
      - name: 'cmake build'
        shell: bash
        run: cmake --build build --config Release --parallel
      - name: 'cmake install'
        shell: bash
        run: cmake --install build --config Release
      - name: 'Store source archives'
        uses: actions/upload-artifact@v4
        with:
          name: 'SDL2-windows-${{steps.json_properties.outputs.tag}}'
          path: '${{ github.workspace}}/install'
