name: 'release'
run-name: 'Create SDL release artifacts for ${{ inputs.commit }}'

on:
  workflow_dispatch:

jobs:
  src:
    runs-on: ubuntu-latest
    outputs:
      project: ${{ steps.releaser.outputs.project }}
      version: ${{ steps.releaser.outputs.version }}
      src-zip: ${{ steps.releaser.outputs.src-zip }}
    steps:
      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: 'Checkout SDL sources'
        uses: actions/checkout@v4
        with:
          repository: 'libsdl-org/SDL'
          ref: 'release-2.30.10'
          path: 'SDL'
          fetch-depth: 0
#      - name: 'Read json config'
      # todo
      - name: 'Build Source archive'
        id: releaser
        shell: bash
        run: |
          ls -l
          python build-scripts/build-release.py \
            --actions source \
            --commit 9c821dc21ccbd69b2bda421fdb35cb4ae2da8f5e \
            --root "${{ github.workspace }}/SDL" \
            --github \
            --debug
      - name: 'Store source archives'
        uses: actions/upload-artifact@v4
        with:
          name: sources
          path: '${{ github.workspace}}/dist'