name: 'sdl2'
run-name: 'Create SDL release artifacts for ${{ inputs.commit }}'

on:
  workflow_dispatch:

jobs:
  msvc:
    runs-on: windows-latest
    steps:
      - name: 'Checkout SDL sources'
        uses: actions/checkout@v4
        with:
          repository: 'libsdl-org/SDL'
          ref: 'release-2.30.10'
          fetch-depth: 0
      - name: 'cmake configure'
        shell: bash
        run: |
          cmake -B build \
               -DSDL_WERROR=ON \
               -DSDL_STATIC=OFF \
               -DSDL_TEST=OFF \
               -DSDL_TESTS=OFF \
               -DSDL_INSTALL_TESTS=OFF \
               -DSDL2_DISABLE_INSTALL=OFF \
               -A x64 \
               -DCMAKE_INSTALL_PREFIX=install \
               -DCMAKE_BUILD_TYPE=Release
      - name: 'cmake build'
        shell: bash
        run: cmake --build build --config Release --parallel
      - name: 'cmake install'
        shell: bash
        run: cmake --install build --config Release
      - name: 'Publish artifacts'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "install/*"
          allowUpdates: true
          name: 'release-2.30.10'
#      - name: 'Store source archives'
#        uses: actions/upload-artifact@v4
#        with:
#          name: windows
#          path: '${{ github.workspace}}/install'