name: 'sdl2_mixer wasm'
run-name: 'Build SDL2 mixer for wasm'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout config'
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'config.json'
      - name: 'read config.json'
        id: config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "config.json"
      - name: 'Setup Emscripten'
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.74
          actions-cache-folder: 'emsdk-cache'
      - name: 'Setup Ninja'
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.12.1
      - name: 'Fetch SDL2'
        shell: pwsh
        run: |
          $url = 'https://github.com/puzankov-al/ci/releases/download/all/sdl2-wasm-${{ steps.config.outputs.sdl2_tag }}.zip'
          Invoke-WebRequest $url -OutFile ./sdl.zip;
          Expand-Archive -Path sdl.zip;
      - name: 'Checkout source'
        uses: actions/checkout@v4
        with:
          repository: 'libsdl-org/SDL_mixer'
          ref: ${{steps.config.outputs.sdl2_mixer_tag}}
          fetch-depth: 0
          path: 'source'
          submodules: recursive
      - name: 'Patch SDL2_mixer'
        shell: bash
        run: 'cd source && git apply ../patch/sdl2_mixer.patch'
      - name: 'cmake configure'
        shell: bash
        run: |
          emcmake cmake -S source -B build \
                -G Ninja \
                -DBUILD_SHARED_LIBS=OFF \
                -DSDL2MIXER_DEPS_SHARED=OFF \
                -DSDL2MIXER_VENDORED=ON \
                -DSDL2MIXER_MOD=OFF \
                -DSDL2MIXER_OPUS=OFF \
                -DSDL2MIXER_WAVE=OFF \
                -DSDL2MIXER_WAVPACK=OFF \
                -DSDL2MIXER_FLAC=OFF \
                -DSDL2MIXER_GME=OFF \
                -DSDL2MIXER_MIDI=OFF \
                -DCMAKE_INSTALL_PREFIX=install \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_PREFIX_PATH='${{ github.workspace }}/sdl/lib/cmake/SDL2' \
                -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=NEVER
      - name: 'cmake build'
        shell: bash
        run: cmake --build build --config Release --parallel
      - name: 'cmake install'
        shell: bash
        run: cmake --install build --config Release
      - name: 'Store source archives'
        uses: actions/upload-artifact@v4
        with:
          name: 'sdl2_mixer-wasm-${{steps.config.outputs.sdl2_mixer_tag}}'
          path: '${{ github.workspace}}/install'
