name: 'sdl2_ttf ios'
run-name: 'Build SDL2 ttf for ios'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'read config.json'
        id: config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "config.json"
      - name: 'Checkout source'
        uses: actions/checkout@v4
        with:
          repository: 'libsdl-org/SDL_ttf'
          ref: ${{steps.config.outputs.sdl2_ttf_tag}}
          fetch-depth: 0
          path: 'source'
          submodules: recursive
      - name: 'Patch SDL2_ttf'
        shell: bash
        working-directory: source
        run: git apply ../patch/sdl2_ttf.patch
      - name: 'xcode build'
        shell: bash
        run: |
          IPHONEOS_ARCHIVE_PATH="${{ github.workspace }}/install/SDL2_ttf-iphoneos.xcarchive"
          IPHONESIMULATOR_ARCHIVE_PATH="${{ github.workspace }}/install/SDL2_ttf-iphonesimulator.xcarchive"

          # todo: Framework schema compilation is broken for iphonesimulator
          xcodebuild archive \
                     -project source/Xcode/SDL_ttf.xcodeproj \
                     -scheme 'Static Library' \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $IPHONEOS_ARCHIVE_PATH

          xcodebuild archive \
                     PLATFORM=iOS \
                     -project source/Xcode/SDL_ttf.xcodeproj \
                     -scheme 'Static Library' \
                     -configuration Release \
                     -sdk iphonesimulator \
                     -archivePath $IPHONESIMULATOR_ARCHIVE_PATH

          mkdir source/include
          cp source/SDL_ttf.h source/include

          xcodebuild -create-xcframework \
                     -library "$IPHONEOS_ARCHIVE_PATH/Products/usr/local/lib/libSDL2_ttf.a" \
                     -headers source/include \
                     -library "$IPHONESIMULATOR_ARCHIVE_PATH/Products/usr/local/lib/libSDL2_ttf.a" \
                     -headers source/include \
                     -output install/xcframework/SDL2_ttf.xcframework

      - name: 'Store source archives'
        uses: actions/upload-artifact@v4
        with:
          name: 'sdl2_ttf-ios-${{steps.config.outputs.sdl2_ttf_tag}}'
          path: '${{ github.workspace}}/install/xcframework'
