name: 'sdl2 ios'
run-name: 'Build SDL2 for iOS'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'read config.json'
        id: config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "config.json"
      - name: 'Checkout source'
        uses: actions/checkout@v4
        with:
          repository: 'libsdl-org/SDL'
          ref: ${{steps.config.outputs.sdl2_tag}}
          fetch-depth: 0
          path: 'source'
      - name: 'xcodebuild'
        shell: bash
        run: |
          xcodebuild -project source/Xcode/SDL/SDL.xcodeproj \
                     -target 'xcFramework-iOS' \
                     -configuration Release
      - name: 'Store source archives'
        uses: actions/upload-artifact@v4
        with:
          name: 'sdl2-ios-${{steps.config.outputs.sdl2_tag}}'
          path: '${{ github.workspace}}/source/Xcode/SDL/Products'
