name: 'sdl2_mixer windows'
run-name: 'Build SDL2 mixer for windows'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: 'Checkout config'
        uses: actions/checkout@v4
        with:
          path: 'config'
          sparse-checkout: 'sdl2_mixer'
      - name: 'read config.json'
        id: config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "config/sdl2_mixer/config.json"
      - name: 'Fetch SDL2'
        shell: pwsh
        run: |
          $url = '${{ steps.config.outputs.sdl_windows_url }}';
          Write-Host $url;
          Invoke-WebRequest $url -OutFile ./sdl.zip;
          Expand-Archive -Path sdl.zip;
      - name: 'Checkout source'
        uses: actions/checkout@v4
        with:
          repository: 'libsdl-org/SDL_mixer'
          ref: ${{steps.config.outputs.sdl_mixer_tag}}
          fetch-depth: 0
          path: 'source'
          submodules: recursive
      - name: Setup MSVC dependencies
        shell: pwsh
        run: |
          echo "::group::Downloading yasm"
          source/.github/fetch_yasm.ps1
          echo "${{ github.workspace }}" >> $Env:GITHUB_PATH
          echo "::endgroup::"
      - name: 'Patch SDL2_mixer'
        shell: bash
        run: 'cd source && git apply ../config/sdl2_mixer/sdl2_mixer.patch'
      - name: 'cmake configure'
        shell: bash
        run: |
          cmake -S source -B build \
                -A x64 \
                -DSDL2MIXER_VENDORED=ON \
                -DSDL2MIXER_MOD=OFF \
                -DSDL2MIXER_OPUS=OFF \
                -DSDL2MIXER_WAVE=OFF \
                -DSDL2MIXER_WAVPACK=OFF \
                -DSDL2MIXER_FLAC=OFF \
                -DSDL2MIXER_GME=OFF \
                -DSDL2MIXER_MIDI=OFF \
                -DCMAKE_INSTALL_PREFIX=install \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_PREFIX_PATH='${{ github.workspace }}/sdl/cmake'
      - name: 'cmake build'
        shell: bash
        run: cmake --build build --config Release --parallel
      - name: 'cmake install'
        shell: bash
        run: cmake --install build --config Release
      - name: 'Store source archives'
        uses: actions/upload-artifact@v4
        with:
          name: 'sdl2_mixer-windows-${{steps.config.outputs.sdl_mixer_tag}}'
          path: '${{ github.workspace}}/install'
