name: 'sdl2 mixer'
run-name: 'Build SDL2 mixer'

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: 'Setup Ninja'
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.12.1
      - name: Setup MSVC dependencies
        if: "matrix.platform.msvc"
        shell: pwsh
        run: |
          echo "::group::Downloading SDL"
          .github/fetch_sdl_vc.ps1
          echo "SDL2_DIR=$Env:GITHUB_WORKSPACE/SDL2-devel-VC" >> $Env:GITHUB_ENV
          echo "::endgroup::"
          echo "::group::Downloading yasm"
          .github/fetch_yasm.ps1
          echo "${{ github.workspace }}" >> $Env:GITHUB_PATH
          echo "::endgroup::"
      - uses: ilammy/msvc-dev-cmd@v1
        if: "matrix.platform.msvc"
        with:
          arch: x64
      - name: 'Checkout config'
        uses: actions/checkout@v4
        with:
          path: 'config'
          sparse-checkout: 'sdl2_mixer'
      - name: 'read config.json'
        id: config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "config/sdl2_mixer/config.json"
      - name: 'Checkout source'
        uses: actions/checkout@v4
        with:
          repository: 'libsdl-org/SDL_mixer'
          ref: ${{steps.config.outputs.sdl_mixer_tag}}
          fetch-depth: 0
          path: 'source'
          submodules: recursive
      - name: 'cmake configure'
        shell: bash
        run: |
          cmake -S source -B build \
                -GNinja \
#                -A x64 \
                -DSDL2MIXER_VENDORED=ON
                -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
                -DCMAKE_BUILD_TYPE=Release \
                -DSDL2MIXER_MP3_MPG123=ON \
                -DSDL2MIXER_VORBIS=VORBISFILE \
                -DCMAKE_INSTALL_PREFIX=install
          
#               -DSDL_WERROR=ON \
#               -DSDL_STATIC=OFF \
#               -DSDL_TEST=OFF \
#               -DSDL_TESTS=OFF \
#               -DSDL_INSTALL_TESTS=OFF \
#               -DSDL2_DISABLE_INSTALL=OFF \
#               -A x64 \
#               -DCMAKE_INSTALL_PREFIX=install \
#               -DCMAKE_BUILD_TYPE=Release
      - name: 'cmake build'
        shell: bash
        run: cmake --build build --config Release --parallel
      - name: 'cmake install'
        shell: bash
        run: cmake --install build --config Release
      - name: 'Store source archives'
        uses: actions/upload-artifact@v4
        with:
          name: 'sdl2_mixer-windows-${{steps.config.outputs.sdl_mixer_tag}}'
          path: '${{ github.workspace}}/install'