name: 'sdl2_mixer ios'
run-name: 'Build SDL2 mixer for ios'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: 'Setup Macos dependencies'
        run: |
          brew install \
            autoconf \
            automake \
            libtool \
            pkg-config \
            flac \
            fluidsynth \
            game-music-emu \
            libvorbis \
            libxmp \
            mpg123 \
            opusfile \
            wavpack
      - name: 'Checkout config'
        uses: actions/checkout@v4
        with:
          path: 'config'
          sparse-checkout: 'sdl2_mixer'
      - name: 'read config.json'
        id: config
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "config/sdl2_mixer/config.json"
      - name: 'Checkout source'
        uses: actions/checkout@v4
        with:
          repository: 'libsdl-org/SDL_mixer'
          ref: ${{steps.config.outputs.sdl_mixer_tag}}
          fetch-depth: 0
          path: 'source'
          submodules: recursive
      - name: 'Patch SDL2_mixer'
        shell: bash
        run: 'cd source && git apply ../config/sdl2_mixer/sdl2_mixer.patch'
      - name: 'xcode build'
        shell: bash
        run: |
          IPHONEOS_ARCHIVE_PATH="${{ github.workspace }}/install/SDL2_mixer-iphoneos.xcarchive"
          IPHONESIMULATOR_ARCHIVE_PATH="${{ github.workspace }}/install/SDL2_mixer-iphonesimulator.xcarchive"

          # todo: Framework schema compilation is broken for iphonesimulator
          xcodebuild archive \
                     -project source/Xcode/SDL_mixer.xcodeproj \
                     -scheme 'Static Library' \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $IPHONEOS_ARCHIVE_PATH

          xcodebuild archive \
                     PLATFORM=iOS \
                     -project source/Xcode/SDL_mixer.xcodeproj \
                     -scheme 'Static Library' \
                     -configuration Release \
                     -sdk iphonesimulator \
                     -archivePath $IPHONESIMULATOR_ARCHIVE_PATH

          xcodebuild -create-xcframework \
                     -library "$IPHONEOS_ARCHIVE_PATH/Products/usr/local/lib/libSDL2_mixer.a" \
                     -headers source/include \
                     -library "$IPHONESIMULATOR_ARCHIVE_PATH/Products/usr/local/lib/libSDL2_mixer.a" \
                     -headers source/include \
                     -output install/xcframework/SDL2_mixer.xcframework
      - name: 'Store source archives'
        uses: actions/upload-artifact@v4
        with:
          name: 'sdl2_mixer-ios-${{steps.config.outputs.sdl_mixer_tag}}'
          path: '${{ github.workspace}}/install/xcframework'
